Backup/Models/Article.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using PetaPoco;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace PetaPocoWebTest.Poco
{
	public class Article
	{
		public int Id {get; set;}
		public string Title {get; set;}
		public string Body {get; set;}

		[DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode=true)]
		public DateTime Date {get; set;}

		[ResultColumn]
		public Author Author {get; set;}

		[Column( "author_id")]
		[DisplayName( "Author")]
		public int? AuthorId {get; set;}

		[ResultColumn]
		public List<Tag> Tags {get; set;}

		public Article()
		{
			Date = DateTime.Now;
			Id = int.MinValue;
			Tags = new List<Tag>();
		}
	}
}

Backup/ViewModels/ArticlesViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using PetaPocoWebTest.Poco;

namespace PetaPocoWebTest.ViewModels
{
	public class ArticlesViewModel
	{
		public List<Article> Articles {get; set;}
		public List<Author> Authors {get; set;}
	}
}

Backup/Controllers/ArticleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PetaPocoWebTest.Poco;
using PetaPocoWebTest.ViewModels;
using PetaPocoWebTest.Database;
using System.Text.RegularExpressions;

namespace PetaPocoWebTest.Controllers
{
    public class ArticleController : BaseController
    {
		public ArticleController()
		{
			ThisControllerLivesInWebsiteSection( "article");
		}

        //
        // GET: /Article/
        public ActionResult Index()
        {
			ArticlesViewModel viewModel =
				new ArticlesViewModel()
				{
					Articles = _articles.RetrieveAll(),
					Authors = null
				};

            return View( viewModel);
        }

        //
        // GET: /Article/Details/5
        public ActionResult Details(int articleId)
        {
			var article = _articles.RetrieveById( articleId);
            return View( article);
        }

        //
        // GET: /Article/Create
        public ActionResult Create()
        {
			var viewModel = new ArticleEditViewModel()
			{
				Article = new Article(),
				Authors = _authors.RetrieveAll(),
				Tags = _tags.RetrieveAll()
			};

            return View( viewModel);
        } 

        //
        // POST: /Article/Create
        [HttpPost]
        public ActionResult Create( Article article)
        {
            try
            {
                _articles.Insert( ParseTags( article));
                return RedirectToAction("Index");
            }
            catch( Exception exception)
            {
				ViewBag.ErrorMessage = exception.Message;
				var viewModel = new ArticleEditViewModel()
				{
					Article = article,
					Authors = _authors.RetrieveAll(),
					Tags = _tags.RetrieveAll()
				};

                return View( viewModel);
            }
        }
        
        //
        // GET: /Article/Edit/5
        public ActionResult Edit(int articleId)
        {
			var viewModel = new ArticleEditViewModel()
			{
				Article = _articles.RetrieveById( articleId),
				Authors = _authors.RetrieveAll(),
				Tags = _tags.RetrieveAll()
			};

            return View( viewModel);
        }

        //
        // POST: /Article/Edit/5
        [HttpPost]
        public ActionResult Edit( Article article)
        {
            try
            {
                _articles.Update( ParseTags( article));
                return RedirectToAction("Index");
            }
            catch( Exception exception)
            {
				ViewBag.ErrorMessage = exception.Message;
				var viewModel = new ArticleEditViewModel()
				{
					Article = article,
					Authors = _authors.RetrieveAll(),
					Tags = _tags.RetrieveAll()
				};

                return View( viewModel);
            }
        }

		private Article ParseTags( Article article)
		{
			var editedTags = Request["Tags"];
			if( ! string.IsNullOrEmpty( editedTags))
			{
				var tags = Regex.Split( editedTags, "\r\n");
				if( tags != null && tags.Length > 0)
				{
					foreach( var tag in tags)
					{
						article.Tags.Add( new Tag( tag));
					}
				}
			}

			return article;
		}

        //
        // GET: /Article/Delete/5
        public ActionResult Delete( int articleId)
        {
			var article = _articles.RetrieveById( articleId);

            return View( article);
        }

        //
        // POST: /Article/Delete/5
        [HttpPost]
        public ActionResult Delete( int articleId, FormCollection formCollection/*dummy parameter for function signature difference*/)
        {
            try
            {
                _articles.Delete( articleId);
                return RedirectToAction("Index");
            }
            catch( Exception exception)
            {
				ViewBag.ErrorMessage = exception.Message;
                return View( _articles.RetrieveById( articleId));
            }
        }
    }
}

Backup/Controllers/AuthorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PetaPocoWebTest.Poco;
using PetaPocoWebTest.Database;

namespace PetaPocoWebTest.Controllers
{
    public class AuthorController : BaseController
    {
		public AuthorController()
		{
			ThisControllerLivesInWebsiteSection( "author");
		}

        //
        // GET: /Author/
        public ActionResult Index()
        {
			List<Author> Authors = _authors.RetrieveAll();
            return View( Authors);
        }

        //
        // GET: /Author/Details/5
        public ActionResult Details( int authorId)
        {
			var author = _authors.RetrieveById( authorId);
            return View( author);
        }

        //
        // GET: /Author/Create
        public ActionResult Create()
        {
            return View( new Author());
        } 

        //
        // POST: /Author/Create
        [HttpPost]
        public ActionResult Create( Author author)
        {
            try
            {
                _authors.Insert( author);
                return RedirectToAction("Index");
            }
            catch( Exception exception)
            {
				ViewBag.ErrorMessage = exception.Message;
                return View( author);
            }
        }
        
        //
        // GET: /Author/Edit/5
        public ActionResult Edit(int authorId)
        {
			var author = _authors.RetrieveById( authorId);
            return View( author);
        }

        //
        // POST: /Author/Edit/5
        [HttpPost]
        public ActionResult Edit( Author author)
        {
            try
            {
                _authors.Update( author);
                return RedirectToAction("Index");
            }
            catch( Exception exception)
            {
				ViewBag.ErrorMessage = exception.Message;
                return View();
            }
        }

        //
        // GET: /Author/Delete/5
        public ActionResult Delete( int authorId)
        {
			var author = _authors.RetrieveById( authorId);

            return View( author);
        }

        //
        // POST: /Author/Delete/5
        [HttpPost]
        public ActionResult Delete( int authorId, FormCollection formCollection)
        {
            try
            {
                _authors.Delete( authorId);
                return RedirectToAction("Index");
            }
            catch( Exception exception)
            {
				ViewBag.ErrorMessage = exception.Message;
                return View( _authors.RetrieveById( authorId));
            }
        }
    }
}

Backup/Controllers/TagController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PetaPocoWebTest.Poco;
using PetaPocoWebTest.ViewModels;
using PetaPocoWebTest.Database;
using System.Text.RegularExpressions;

namespace PetaPocoWebTest.Controllers
{
    public class TagController : BaseController
    {
		public TagController()
		{
			ThisControllerLivesInWebsiteSection( "tag");
		}

        //
        // GET: /tag/
        public ActionResult Index()
        {
			return View( _tags.RetrieveAll());
        }

        //
        // GET: /tag/Details/tagName
        public ActionResult Details( string tagName)
        {
			var tag = _tags.RetrieveByTag( tagName);
            return View( tag);
        }

        //
        // GET: /tag/Create
        public ActionResult Create()
        {
            return View( new Tag());
        } 

        //
        // POST: /tag/Create
        [HttpPost]
        public ActionResult Create( Tag tag)
        {
            try
            {
                _tags.Insert( tag);
                return RedirectToAction("Index");
            }
            catch( Exception exception)
            {
				ViewBag.ErrorMessage = exception.Message;
                return View( tag);
            }
        }
        
        //
        // GET: /tag/Edit/5
        public ActionResult Edit( string tagName)
        {
            return View( _tags.RetrieveByTag( tagName));
        }

        //
        // POST: /tag/Edit/5
        [HttpPost]
        public ActionResult Edit( Tag tag)
        {
            try
            {
                _tags.Update( tag);
                return RedirectToAction("Index");
            }
            catch( Exception exception)
            {
				ViewBag.ErrorMessage = exception.Message;
                return View( tag);
            }
        }

        //
        // GET: /tag/Delete/5
        public ActionResult Delete( string tagName)
        {
            return View( _tags.RetrieveByTag( tagName));
        }

        //
        // POST: /tag/Delete/5
        [HttpPost]
        public ActionResult Delete( int tagId)
        {
            try
            {
                _tags.Delete( tagId);
                return RedirectToAction("Index");
            }
            catch( Exception exception)
            {
				ViewBag.ErrorMessage = exception.Message;
                return View( _tags.RetrieveById( tagId));
            }
        }
    }
}

Backup/Views/Article/Create.cshtml
@model PetaPocoWebTest.ViewModels.ArticleEditViewModel

@{
    ViewBag.Title = "Create";
}

@section onReadyJavascript {
$("#Article_Date").datepicker(
    {
        "dateFormat" : "dd/mm/yy"
    });
}

<h2>Create new article</h2>

<p>
    @Html.ActionLink("Home", "Index", "Home") - @Html.ActionLink("Back to list of articles", "Index")
</p>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Article</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Article.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Article.Title)
            @Html.ValidationMessageFor(model => model.Article.Title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Article.Body)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Article.Body)
            @Html.ValidationMessageFor(model => model.Article.Body)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Article.Date)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Article.Date)
            @Html.ValidationMessageFor(model => model.Article.Date)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Article.AuthorId)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor( model => model.Article.AuthorId, new SelectList( Model.Authors, "Id", "Name", Model.Article.AuthorId))
            @Html.ValidationMessageFor(model => model.Article.AuthorId)
        </div>

        @{Html.RenderPartial( "TagsControl", Model.Article.Tags, new ViewDataDictionary() {{"AllTags", Model.Tags}});}
        @Html.ValidationMessageFor(model => model.Article.AuthorId)

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

Backup/Views/Article/Delete.cshtml
@model PetaPocoWebTest.Poco.Article

@{
    ViewBag.Title = "Delete";
}

<h2>Delete article : @Model.Title</h2>
<p>
    @Html.ActionLink("Home", "Index", "Home") - @Html.ActionLink("Back to list of articles", "Index")
</p>
<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Article</legend>

    <div class="display-label">Title</div>
    <div class="display-field">@Model.Title</div>

    <div class="display-label">Body</div>
    <div class="display-field">@Model.Body</div>

    <div class="display-label">Date</div>
    <div class="display-field">@String.Format("{0:g}", Model.Date)</div>

    <div class="display-label">AuthorId</div>
    <div class="display-field">@Model.Author.Name</div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" />
    </p>
}

Backup/Views/Article/Details.cshtml
@model PetaPocoWebTest.Poco.Article

@{
    ViewBag.Title = "Details";
}

<h2>Article : @Model.Title</h2>
<p>
    @Html.ActionLink("Home", "Index", "Home") - @Html.ActionLink("Edit", "Edit", new { articleId=Model.Id }) - @Html.ActionLink("Back to list of articles", "Index")
</p>
<fieldset>
    <legend>Article</legend>

    <div class="display-label">Title</div>
    <div class="display-field">@Model.Title</div>

    <div class="display-label">Body</div>
    <div class="display-field">@Model.Body</div>

    <div class="display-label">Date</div>
    <div class="display-field">@String.Format("{0:g}", Model.Date)</div>

    <div class="display-label">Author</div>
    <div class="display-field">
    @Html.ActionLink( Model.Author.Name, "Details", "Author", new {authorId=Model.Author.Id}, null)
    </div>

    <div class="display-label">Tags</div>
    <div class="display-field">
    @foreach( var tag in Model.Tags){ <text><a href="@Url.Action( "Details", "Tag", new {tagName=tag.TagName})">@tag.TagName</a></text>}
    </div>
</fieldset>

Backup/Views/Article/Edit.cshtml
@model PetaPocoWebTest.ViewModels.ArticleEditViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit article : @Model.Article.Title</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Article</legend>

        @Html.HiddenFor(model => model.Article.Id)

        <div class="editor-label">
            @Html.LabelFor(model => model.Article.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Article.Title)
            @Html.ValidationMessageFor(model => model.Article.Title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Article.Body)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Article.Body)
            @Html.ValidationMessageFor(model => model.Article.Body)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Article.Date)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Article.Date)
            @Html.ValidationMessageFor(model => model.Article.Date)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Article.AuthorId)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor( model => model.Article.AuthorId, new SelectList( Model.Authors, "Id", "Name", Model.Article.AuthorId))
            @Html.ValidationMessageFor(model => model.Article.AuthorId)
        </div>

        @{Html.RenderPartial( "TagsControl", Model.Article.Tags, new ViewDataDictionary() {{"AllTags", Model.Tags}});}
        @Html.ValidationMessageFor(model => model.Article.AuthorId)

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to list of articles", "Index")
</div>

Backup/Views/Article/Index.cshtml
@model PetaPocoWebTest.ViewModels.ArticlesViewModel

@{
    ViewBag.Title = "Index";
}

<h2>Articles</h2>

<p>
    @Html.ActionLink("Home", "Index", "Home") - @Html.ActionLink("Create new article", "Create")
</p>

@if( Model.Articles.Count == 0){

    <p>There are no articles yet</p>

}else{

    <table id="example">
        <thead>
            <tr>
                <th></th>
                <th>Title</th>
                <th>Author</th>
                <th>Date</th>
                <th>Id</th>
                <th>Tags</th>
            </tr>
        </thead>

        <tbody>
            @foreach( var article in Model.Articles) {
            <tr>
                <td>
                    @Html.ActionLink("Edit", "Edit", new {articleId=article.Id}) |
                    @Html.ActionLink("Details", "Details", new {articleId=article.Id}) |
                    @Html.ActionLink("Delete", "Delete", new {articleId=article.Id})
                </td>
                <td>
                    @article.Title
                </td>
                <td>
                    @article.Author.Name
                </td>
                <td>
                    @article.Date.ToShortDateString() @article.Date.ToShortTimeString()
                </td>
                <td>
                    @article.Id
                </td>
                <td>
                    @foreach( var tag in article.Tags){ <text><a href="@Url.Action( "Details", "Tag", new {tagName=tag.TagName})">@tag.TagName</a></text>}
                </td>
            </tr>
            }
        </tbody>
    </table>
}