Backup/Models/Tag.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using PetaPoco;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace PetaPocoWebTest.Poco
{
	[TableName( "tag")]
	public class Tag
	{
		public int Id {get; set;}

		[Column( "tagName")]
		public string TagName {get; set;}

		public Tag() : this( string.Empty)
		{
		}

		[ResultColumn]
		public List<Article> Articles {get; set;}

		public override string ToString()
		{
			return this.TagName;
		}

		public Tag( string tagName)
		{
			this.TagName = tagName;
			this.Id = int.MinValue;
			this.Articles = new List<Article>();
		}
	}
}

Backup/Controllers/ArticleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PetaPocoWebTest.Poco;
using PetaPocoWebTest.ViewModels;
using PetaPocoWebTest.Database;
using System.Text.RegularExpressions;

namespace PetaPocoWebTest.Controllers
{
    public class ArticleController : BaseController
    {
		public ArticleController()
		{
			ThisControllerLivesInWebsiteSection( "article");
		}

        //
        // GET: /Article/
        public ActionResult Index()
        {
			ArticlesViewModel viewModel =
				new ArticlesViewModel()
				{
					Articles = _articles.RetrieveAll(),
					Authors = null
				};

            return View( viewModel);
        }

        //
        // GET: /Article/Details/5
        public ActionResult Details(int articleId)
        {
			var article = _articles.RetrieveById( articleId);
            return View( article);
        }

        //
        // GET: /Article/Create
        public ActionResult Create()
        {
			var viewModel = new ArticleEditViewModel()
			{
				Article = new Article(),
				Authors = _authors.RetrieveAll(),
				Tags = _tags.RetrieveAll()
			};

            return View( viewModel);
        } 

        //
        // POST: /Article/Create
        [HttpPost]
        public ActionResult Create( Article article)
        {
            try
            {
                _articles.Insert( ParseTags( article));
                return RedirectToAction("Index");
            }
            catch( Exception exception)
            {
				ViewBag.ErrorMessage = exception.Message;
				var viewModel = new ArticleEditViewModel()
				{
					Article = article,
					Authors = _authors.RetrieveAll(),
					Tags = _tags.RetrieveAll()
				};

                return View( viewModel);
            }
        }
        
        //
        // GET: /Article/Edit/5
        public ActionResult Edit(int articleId)
        {
			var viewModel = new ArticleEditViewModel()
			{
				Article = _articles.RetrieveById( articleId),
				Authors = _authors.RetrieveAll(),
				Tags = _tags.RetrieveAll()
			};

            return View( viewModel);
        }

        //
        // POST: /Article/Edit/5
        [HttpPost]
        public ActionResult Edit( Article article)
        {
            try
            {
                _articles.Update( ParseTags( article));
                return RedirectToAction("Index");
            }
            catch( Exception exception)
            {
				ViewBag.ErrorMessage = exception.Message;
				var viewModel = new ArticleEditViewModel()
				{
					Article = article,
					Authors = _authors.RetrieveAll(),
					Tags = _tags.RetrieveAll()
				};

                return View( viewModel);
            }
        }

		private Article ParseTags( Article article)
		{
			var editedTags = Request["Tags"];
			if( ! string.IsNullOrEmpty( editedTags))
			{
				var tags = Regex.Split( editedTags, "\r\n");
				if( tags != null && tags.Length > 0)
				{
					foreach( var tag in tags)
					{
						article.Tags.Add( new Tag( tag));
					}
				}
			}

			return article;
		}

        //
        // GET: /Article/Delete/5
        public ActionResult Delete( int articleId)
        {
			var article = _articles.RetrieveById( articleId);

            return View( article);
        }

        //
        // POST: /Article/Delete/5
        [HttpPost]
        public ActionResult Delete( int articleId, FormCollection formCollection/*dummy parameter for function signature difference*/)
        {
            try
            {
                _articles.Delete( articleId);
                return RedirectToAction("Index");
            }
            catch( Exception exception)
            {
				ViewBag.ErrorMessage = exception.Message;
                return View( _articles.RetrieveById( articleId));
            }
        }
    }
}

Backup/Controllers/AuthorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PetaPocoWebTest.Poco;
using PetaPocoWebTest.Database;

namespace PetaPocoWebTest.Controllers
{
    public class AuthorController : BaseController
    {
		public AuthorController()
		{
			ThisControllerLivesInWebsiteSection( "author");
		}

        //
        // GET: /Author/
        public ActionResult Index()
        {
			List<Author> Authors = _authors.RetrieveAll();
            return View( Authors);
        }

        //
        // GET: /Author/Details/5
        public ActionResult Details( int authorId)
        {
			var author = _authors.RetrieveById( authorId);
            return View( author);
        }

        //
        // GET: /Author/Create
        public ActionResult Create()
        {
            return View( new Author());
        } 

        //
        // POST: /Author/Create
        [HttpPost]
        public ActionResult Create( Author author)
        {
            try
            {
                _authors.Insert( author);
                return RedirectToAction("Index");
            }
            catch( Exception exception)
            {
				ViewBag.ErrorMessage = exception.Message;
                return View( author);
            }
        }
        
        //
        // GET: /Author/Edit/5
        public ActionResult Edit(int authorId)
        {
			var author = _authors.RetrieveById( authorId);
            return View( author);
        }

        //
        // POST: /Author/Edit/5
        [HttpPost]
        public ActionResult Edit( Author author)
        {
            try
            {
                _authors.Update( author);
                return RedirectToAction("Index");
            }
            catch( Exception exception)
            {
				ViewBag.ErrorMessage = exception.Message;
                return View();
            }
        }

        //
        // GET: /Author/Delete/5
        public ActionResult Delete( int authorId)
        {
			var author = _authors.RetrieveById( authorId);

            return View( author);
        }

        //
        // POST: /Author/Delete/5
        [HttpPost]
        public ActionResult Delete( int authorId, FormCollection formCollection)
        {
            try
            {
                _authors.Delete( authorId);
                return RedirectToAction("Index");
            }
            catch( Exception exception)
            {
				ViewBag.ErrorMessage = exception.Message;
                return View( _authors.RetrieveById( authorId));
            }
        }
    }
}

Backup/Controllers/TagController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PetaPocoWebTest.Poco;
using PetaPocoWebTest.ViewModels;
using PetaPocoWebTest.Database;
using System.Text.RegularExpressions;

namespace PetaPocoWebTest.Controllers
{
    public class TagController : BaseController
    {
		public TagController()
		{
			ThisControllerLivesInWebsiteSection( "tag");
		}

        //
        // GET: /tag/
        public ActionResult Index()
        {
			return View( _tags.RetrieveAll());
        }

        //
        // GET: /tag/Details/tagName
        public ActionResult Details( string tagName)
        {
			var tag = _tags.RetrieveByTag( tagName);
            return View( tag);
        }

        //
        // GET: /tag/Create
        public ActionResult Create()
        {
            return View( new Tag());
        } 

        //
        // POST: /tag/Create
        [HttpPost]
        public ActionResult Create( Tag tag)
        {
            try
            {
                _tags.Insert( tag);
                return RedirectToAction("Index");
            }
            catch( Exception exception)
            {
				ViewBag.ErrorMessage = exception.Message;
                return View( tag);
            }
        }
        
        //
        // GET: /tag/Edit/5
        public ActionResult Edit( string tagName)
        {
            return View( _tags.RetrieveByTag( tagName));
        }

        //
        // POST: /tag/Edit/5
        [HttpPost]
        public ActionResult Edit( Tag tag)
        {
            try
            {
                _tags.Update( tag);
                return RedirectToAction("Index");
            }
            catch( Exception exception)
            {
				ViewBag.ErrorMessage = exception.Message;
                return View( tag);
            }
        }

        //
        // GET: /tag/Delete/5
        public ActionResult Delete( string tagName)
        {
            return View( _tags.RetrieveByTag( tagName));
        }

        //
        // POST: /tag/Delete/5
        [HttpPost]
        public ActionResult Delete( int tagId)
        {
            try
            {
                _tags.Delete( tagId);
                return RedirectToAction("Index");
            }
            catch( Exception exception)
            {
				ViewBag.ErrorMessage = exception.Message;
                return View( _tags.RetrieveById( tagId));
            }
        }
    }
}

Backup/Views/Tag/Create.cshtml
@model PetaPocoWebTest.Poco.Tag

@{
    ViewBag.Title = "Create";
}

<h2>Create new tag</h2>

<p>
    @Html.ActionLink("Home", "Index", "Home") - @Html.ActionLink("Back to list of tags", "Index")
</p>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Tag</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.TagName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.TagName)
            @Html.ValidationMessageFor(model => model.TagName)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

Backup/Views/Tag/Delete.cshtml
@model PetaPocoWebTest.Poco.Tag

@{
    ViewBag.Title = "Delete";
}

<h2>Delete tag : @Model.TagName</h2>
<p>
    @Html.ActionLink("Home", "Index", "Home") - @Html.ActionLink("Back to list of tags", "Index")
</p>
<h3>Are you sure you want to delete this tag?</h3>
<fieldset>
    <legend>Tag</legend>
    
    <div class="display-label">Tag</div>
    <div class="display-field">@Model.TagName</div>
</fieldset>

@{Html.RenderPartial( "ListArticlesByTag", Model.Articles, new ViewDataDictionary() { {"TagName", Model.TagName}});}

@using (Html.BeginForm()) {
    <input type="hidden" name="tagId" value="@Model.Id" />
    <p>
        <input type="submit" value="Delete" />
    </p>
}

Backup/Views/Tag/Details.cshtml
@model PetaPocoWebTest.Poco.Tag

@{
    ViewBag.Title = "Details";
}

<h2>Tag : @Model.TagName</h2>
<p>
    @Html.ActionLink("Home", "Index", "Home") - @Html.ActionLink("Edit", "Edit", new { tagName=Model.TagName }) - @Html.ActionLink("Back to list of tags", "Index")
</p>
<fieldset>
    <legend>Tag</legend>

    <div class="display-label">Tag name</div>
    <div class="display-field">@Model.TagName</div>
</fieldset>

@{Html.RenderPartial( "ListArticlesByTag", Model.Articles, new ViewDataDictionary() { {"TagName", Model.TagName}});}

    

Backup/Views/Tag/Edit.cshtml
@model PetaPocoWebTest.Poco.Tag

@{
    ViewBag.Title = "Edit";
}

<h2>Edit tag : @Model.TagName</h2>
<p>
    @Html.ActionLink("Home", "Index", "Home") - @Html.ActionLink("Back to list of tags", "Index")
</p>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Tag</legend>

        @Html.HiddenFor(model => model.Id)

        <div class="editor-label">
            @Html.LabelFor(model => model.TagName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.TagName)
            @Html.ValidationMessageFor(model => model.TagName)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

Backup/Views/Tag/Index.cshtml
@model List<PetaPocoWebTest.Poco.Tag>

@{
    ViewBag.Title = "Index";
}

<h2>Tags</h2>

<p>
    @Html.ActionLink("Home", "Index", "Home") - @Html.ActionLink("Create new tag", "Create")
</p>

@if( Model.Count == 0){

    <p>There are no tags yet</p>

}else{

    <table>
        <tr>
            <th></th>
            <th>Name</th>
            <th>Id</th>
            <th>Article count</th>
        </tr>

        @foreach (var tag in Model) {
        <tr>
            <td>
                @Html.ActionLink("Edit", "Edit", new {tagName=tag.TagName}) |
                @Html.ActionLink("Details", "Details", new {tagName=tag.TagName}) |
                @Html.ActionLink("Delete", "Delete", new {tagName=tag.TagName})
            </td>
            <td>
                @tag.TagName
            </td>
            <td>
                @tag.Id
            </td>
            <td style="text-align:right;">
                @tag.Articles.Count()
            </td>
        </tr>
        }

    </table>
}

Backup/Views/Tag/ListArticlesByTag.cshtml
@model List<PetaPocoWebTest.Poco.Article>

<fieldset>
    <legend>Articles tagged '@ViewData["TagName"]'</legend>
    @if( Model.Count > 0){
    <ul>
    @foreach( var article in Model) {
        <li>
            @Html.ActionLink( article.Title, "Details", "Article", new {articleId=article.Id}, null)
            by
            @Html.ActionLink( article.Author.Name, "Details", "Author", new {authorId=article.Author.Id}, null)
        </li>
    }
    </ul>
    } else {
    <p>None</p>
    }
</fieldset>